"""
Agent State Definitions
========================
TypedDict schemas for LangGraph agent state management.

The agent maintains state across conversation turns, enabling:
- Multi-step plan execution
- Context preservation
- Preference learning
- Proactive suggestions
"""

from typing import TypedDict, List, Dict, Any, Optional, Literal
from datetime import datetime


class Message(TypedDict):
    """Single conversation message."""
    role: Literal["user", "assistant", "system", "tool"]
    content: str
    timestamp: str
    tool_calls: Optional[List[Dict[str, Any]]]
    tool_results: Optional[List[Dict[str, Any]]]


class PlanStep(TypedDict):
    """Single step in a multi-step plan."""
    step_number: int
    action: str
    tool_name: Optional[str]
    tool_args: Optional[Dict[str, Any]]
    status: Literal["pending", "in_progress", "completed", "failed"]
    result: Optional[Any]


class UserContext(TypedDict):
    """User profile and preferences for contextual decision-making."""
    user_id: str
    name: Optional[str]
    location: Optional[Dict[str, float]]  # {latitude, longitude}
    address: Optional[str]
    dietary_restrictions: List[str]
    allergies: List[str]
    preferences: Dict[str, Any]  # Learned preferences
    communities: List[str]
    role: Optional[str]  # donor, recipient, volunteer, etc.


class ProactiveSuggestion(TypedDict):
    """Proactive suggestion generated by the agent."""
    type: Literal["reminder", "opportunity", "tip", "milestone"]
    message: str
    priority: Literal["high", "medium", "low"]
    action_required: bool
    action_label: Optional[str]


class ReasoningStep(TypedDict, total=False):
    """One step of explicit ReAct-style reasoning (AGENT_V2)."""
    step: int
    thought: str
    decision: str               # "use_tool" | "ask_clarification" | "respond" | "refuse"
    tool_name: Optional[str]
    confidence: float           # 0..1
    observation: Optional[str]  # result summary after tool fires


class PendingActionEnvelope(TypedDict, total=False):
    """Action queued for user confirmation (AGENT_V2)."""
    pending_id: str
    tool: str
    summary: str
    args: Dict[str, Any]
    expires_at: Optional[str]


class AffectSnapshot(TypedDict, total=False):
    """Classified user affect for this turn (AGENT_V2)."""
    sentiment: float
    urgency: float
    frustration: float
    joy: float
    confusion: float
    dominant: str


class RegisterSnapshot(TypedDict, total=False):
    """Communication register chosen for this turn (AGENT_V2)."""
    tone: str
    verbosity: str
    formality: str
    acknowledgement_required: bool
    notes: List[str]


class GoalSnapshot(TypedDict, total=False):
    """One goal on the agent's stack (AGENT_V2 — Phase 2)."""
    id: str
    user_id: str
    description: str
    intent: str
    status: Literal["open", "in_progress", "blocked", "done", "abandoned"]
    priority: Literal["low", "normal", "high", "urgent"]
    parent_goal_id: Optional[str]
    success_criteria: Optional[str]
    created_at: str
    updated_at: str
    notes: List[str]


class AgentState(TypedDict, total=False):
    """Complete agent state for LangGraph workflow.
    
    This state is persisted to Supabase between conversation turns,
    enabling resumable conversations and contextual awareness.
    """
    # Conversation identity
    conversation_id: str
    user_id: str
    turn_id: str               # AGENT_V2: stable id for this conversation turn
    
    # Message history
    messages: List[Message]
    
    # Current turn state
    current_message: str
    detected_intent: Optional[str]
    detected_language: Literal["en", "es"]
    
    # User context
    user_context: UserContext
    
    # Planning & execution
    active_plan: Optional[List[PlanStep]]
    plan_goal: Optional[str]
    current_step: int
    
    # Tool execution results
    recent_tool_results: List[Dict[str, Any]]
    recent_search_results: Optional[List[Dict[str, Any]]]
    
    # Proactive suggestions
    pending_suggestions: List[ProactiveSuggestion]
    
    # Agent decision-making
    should_suggest_proactively: bool
    requires_user_input: bool
    conversation_phase: Literal[
        "understanding",
        "planning", 
        "executing",
        "confirming",
        "completed",
        "idle"
    ]
    
    # Response generation
    response_text: Optional[str]
    include_audio: bool
    audio_url: Optional[str]

    # ---------------------------------------------------------------
    # AGENT_V2 extensions — all optional, additive only. Legacy graph
    # writes the original fields; v2 graph writes both old and new so
    # downstream code that only knows about the originals keeps working.
    # ---------------------------------------------------------------
    reasoning_trace: List[ReasoningStep]   # ReAct steps for this turn
    confidence: float                       # final-step confidence
    pending_action: Optional[PendingActionEnvelope]  # action awaiting user "yes"
    affect: AffectSnapshot                  # classified inbound affect
    register: RegisterSnapshot              # chosen communication register
    goals: List[GoalSnapshot]               # goal stack for this turn (Phase 2)
    next_step_hint: Optional[str]           # replan suggestion surfaced to next turn (Phase 2)
    self_model_block: Optional[str]         # rendered <self> prompt block
    allowed_tools: List[str]                # scope enforcer output
    blocked_listings: List[Dict[str, Any]]  # listings filtered by FoodSafetyGate
    safety_decision: Optional[Dict[str, Any]]  # input guard / scope decision if not ok
    refusal_text: Optional[str]             # calibrated refusal copy (when blocked)
    agent_v2: bool                          # True when this state was processed by v2 graph
    
    # Metadata
    turn_count: int
    last_updated: str
    error: Optional[str]


class ConversationState(TypedDict):
    """Lightweight state for checkpointing to database."""
    conversation_id: str
    user_id: str
    state_snapshot: Dict[str, Any]  # Serialized AgentState
    checkpoint_type: Literal["turn_end", "plan_step", "manual"]
    created_at: str
